name: Build

on:
  push:
    paths:
      - 'app/**'
      - '.github/workflows/build.yml'
      - 'build.gradle'
      - 'settings.gradle'
      - 'gradle/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, windows-2019 ]

    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
          check-latest: true
      - name: Build with Gradle
        run: ./gradlew :a:assemble
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-artifact
          path: app/build/outputs
