name: Build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'app/**'
      - 'gradle/wrapper/gradle-wrapper.properties'
      - '*.gradle'
  workflow_dispatch:
    inputs:
      release:
        description: 'Release'
        type: boolean
        required: true
        default: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/dists
          key: ${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Build
        run: |
          ./gradlew assemble
          echo "version=$(grep versionName ./app/build.gradle | awk '{print $2}' | tr -d \")" >> $GITHUB_ENV
          echo "commit=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_ENV
      - name: Upload built APKs
        uses: actions/upload-artifact@v3
        with:
          name: BypassDchaLock(v${{ env.version }}@${{ env.commit }})
          path: app/build/outputs/apk/**/*.apk
          if-no-files-found: ignore
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event.inputs.release == 'true' }}
        with:
          tag_name: v${{ env.app_ver }}
          draft: true
          prerelease: false
