name: Build

on:
  push:
    paths:
      - 'app/**'
      - '.github/workflows/build.yml'
      - '*.gradle'
      - 'gradle/**'
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: false
      release:
        description: 'Upload to Release'
        default: false
        required: true
        type: boolean

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.16-101/x64
          key: ${{ hashFiles('**/gradlew') }}
      - if: steps.cache.outputs.cache-hit != 'true'
        name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
          check-latest: true
      - name: Build with Gradle
        run: ./gradlew :a:assemble
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-outputs
          path: app/build/outputs
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event.inputs.release == 'true' }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          draft: true
          prerelease: false
          files: app/build/outputs/apk/debug/app-debug.apk
